### ISSUE TITLE
How up to date is this project

### ISSUE THREAD

**Issue by davidgatti** [simontabor/2fa#5]
@simontabor I just found out about your project and I'm very impressed with the work. I'm considering to use your module. But I have one concern: how up to date is your project? Because I see that the last update was 2 years ago. So there are two options, either:

- you stoped working on this project
- or you did such a good job that there is no point in doing any update.

Let me know :)

**Comment by simontabor** [comment]
Hey @davidgatti! I haven't seen any need to update this project yet... it's still in use in production and is working without any issues.

As it's related to security, any issues that may come up will be fixed, so please do give it a try and let me know how you get on. Cheers!
